Repository Invertus-mollie/PrestaShop, pull requests merged in 2020-12, with the labels that each got.

#176 added new descriptions
  .github/workflows/test.yml
  .php_cs.cache
  mollie.php
  src/Builder/FormBuilder.php
  src/Config/Config.php
  src/Install/Installer.php
  src/Service/SettingsSaveService.php
  upgrade/Upgrade-4.2.0.php
  views/templates/admin/invoice_description.tpl
Labels: 4.2.0

#163 4.2.0 MOL-356 1.7.7 order page design adjustments
  src/Provider/PhoneNumberProvider.php
  views/js/dist/manifest.php
  views/js/dist/transactionOrder.min.js
  views/js/dist/transactionOrder.min.js.map
  views/js/dist/transactionRefund.min.js
  views/js/dist/transactionRefund.min.js.map
  views/js/dist/vendors~app.min.js
  views/js/dist/vendors~app.min.js.map
  views/js/dist/vendors~banks~carrierconfig~methodconfig~transaction.min.js
  views/js/dist/vendors~banks~carrierconfig~methodconfig~transaction.min.js.map
  views/js/src/back/transaction/components/orderlines/OrderLinesInfo.tsx
  views/js/src/back/transaction/components/orderlines/OrderPanel.tsx
  views/js/src/back/transaction/components/orderlines/OrderPanelContent.tsx
  views/js/src/back/transaction/components/orderlines/PaymentInfo.tsx
  views/js/src/back/transaction/components/refund/PaymentInfo.tsx
  views/js/src/back/transaction/components/refund/RefundForm.tsx
  views/js/src/back/transaction/components/refund/RefundInfo.tsx
  views/js/src/back/transaction/components/refund/RefundPanel.tsx
Labels: 4.2.0, WIP

#192 4.2.0 - MOLIM-144 - test api button fix
  config/builder.yml
Labels: 4.2.0

#193 4.2.0 MOLIM-144 translation quotes fix
  mollie.php
Labels: 4.2.0, bug

#194 4.2.0 MOLIM-110 image upgrade
  config/config.yml
  config/service.yml
  logo.gif
  logo.png
  src/Install/Installer.php
  src/Service/OrderStateImageService.php
  upgrade/Upgrade-4.2.0.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/platform_check.php
  views/img/logo_small.png
Labels: 4.2.0, enhancement

#199 Changing phpstan configurations to work for each PS versions individually.
  .github/workflows/test.yml
  tests/phpstan/phpstan.neon
  tests/phpstan/phpstan1.6.1.23.neon
  tests/phpstan/phpstan1.7.6.8.neon
  tests/phpstan/phpstan1.7.7.0.neon
  tests/phpstan/phpstan_base.neon
Labels: enhancement, refactoring

#201 4.2.0 - Fixing workflow tests runner
  .github/workflows/test.yml
Labels: 4.2.0, bug

#197 [Payment method order total feature - PART 3] Payment method order total updater logic addition
  config/config.yml
  config/handler.yml
  config/provider.yml
  config/repository.yml
  config/service.yml
  config/verification.yml
  controllers/admin/AdminMollieAjaxController.php
  mollie.php
  src/Builder/FormBuilder.php
  src/Config/Config.php
  src/Exception/OrderTotalRestrictionException.php
  src/Handler/OrderTotal/OrderTotalUpdaterHandler.php
  src/Handler/OrderTotal/OrderTotalUpdaterHandlerInterface.php
  src/Install/DatabaseTableInstaller.php
  src/Install/DatabaseTableUninstaller.php
  src/Provider/PaymentMethod/PaymentMethodOrderTotalRestrictionProvider.php
  src/Provider/PaymentMethod/PaymentMethodOrderTotalRestrictionProviderInterface.php
  src/Repository/CurrencyRepository.php
  src/Repository/CurrencyRepositoryInterface.php
  src/Service/ApiService.php
  src/Service/EntityManager/EntityManagerInterface.php
  src/Service/EntityManager/ObjectModelManager.php
  src/Service/ExceptionService.php
  src/Service/OrderTotal/OrderTotalRestrictionService.php
  src/Service/OrderTotal/OrderTotalRestrictionServiceInterface.php
  src/Service/PaymentMethod/PaymentMethodOrderRestrictionUpdater.php
  src/Service/PaymentMethod/PaymentMethodOrderRestrictionUpdaterInterface.php
  src/Verification/OrderTotal/CanOrderTotalBeUpdated.php
  src/Verification/OrderTotal/OrderTotalVerificationInterface.php
  tests/Unit/Service/PaymentMethod/PaymentMethodOrderRestrictionUpdaterTest.php
  tests/Unit/Tools/UnitTestCase.php
  tests/Unit/Verification/OrderTotal/CanOrderTotalBeUpdatedTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  views/js/admin/order_total_restriction_refresh.js
  views/templates/admin/_configure/helpers/form/form.tpl
  views/templates/admin/order_total_refresh_results.tpl
Labels: 4.2.0, WIP, enhancement

#196 [Payment method order total feature - PART 2] Payment method order total validation addition
  config/config.yml
  config/handler.yml
  config/provider.yml
  config/repository.yml
  config/service.yml
  config/validator.yml
  config/verification.yml
  controllers/admin/AdminMollieAjaxController.php
  mollie.php
  src/Builder/FormBuilder.php
  src/Config/Config.php
  src/Entity/MolPaymentMethodOrderTotalRestriction.php
  src/Exception/OrderTotalRestrictionException.php
  src/Handler/OrderTotal/OrderTotalUpdaterHandler.php
  src/Handler/OrderTotal/OrderTotalUpdaterHandlerInterface.php
  src/Install/DatabaseTableInstaller.php
  src/Install/DatabaseTableUninstaller.php
  src/Provider/OrderTotal/OrderTotalProvider.php
  src/Provider/OrderTotal/OrderTotalProviderInterface.php
  src/Provider/OrderTotal/OrderTotalRestrictionProvider.php
  src/Provider/OrderTotal/OrderTotalRestrictionProviderInterface.php
  src/Provider/PaymentMethod/PaymentMethodOrderTotalRestrictionProvider.php
  src/Provider/PaymentMethod/PaymentMethodOrderTotalRestrictionProviderInterface.php
  src/Repository/CurrencyRepository.php
  src/Repository/CurrencyRepositoryInterface.php
  src/Repository/MolPaymentMethodOrderTotalRestrictionRepository.php
  src/Repository/MolPaymentMethodOrderTotalRestrictionRepositoryInterface.php
  src/Service/ApiService.php
  src/Service/EntityManager/EntityManagerInterface.php
  src/Service/EntityManager/ObjectModelManager.php
  src/Service/ExceptionService.php
  src/Service/OrderTotal/OrderTotalRestrictionService.php
  src/Service/OrderTotal/OrderTotalRestrictionServiceInterface.php
  src/Service/OrderTotal/OrderTotalService.php
  src/Service/OrderTotal/OrderTotalServiceInterface.php
  src/Service/PaymentMethod/PaymentMethodOrderRestrictionUpdater.php
  src/Service/PaymentMethod/PaymentMethodOrderRestrictionUpdaterInterface.php
  src/Service/PaymentMethod/PaymentMethodRestrictionValidation/BasePaymentMethodRestrictionValidator.php
  src/Verification/OrderTotal/CanOrderTotalBeUpdated.php
  src/Verification/OrderTotal/OrderTotalVerificationInterface.php
  tests/Unit/Service/OrderTotal/OrderTotalServiceTest.php
  tests/Unit/Service/PaymentMethod/PaymentMethodOrderRestrictionUpdaterTest.php
  tests/Unit/Service/PaymentMethod/PaymentMethodRestrictionValidation/BasePaymentRestrictionValidationTest.php
  tests/Unit/Tools/UnitTestCase.php
  tests/Unit/Verification/OrderTotal/CanOrderTotalBeUpdatedTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  views/js/admin/order_total_restriction_refresh.js
  views/templates/admin/_configure/helpers/form/form.tpl
  views/templates/admin/order_total_refresh_results.tpl
Labels: 4.2.0, WIP, enhancement

#206 Feature/system test runner
  .docker/wait-for-container.sh
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  Makefile
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/home_page.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  docker-compose.e2e.local.yml
  docker-compose.e2e.yml
  docker-compose.local.yml
  docker-compose.yml
  tests/seed/database/prestashop_17.sql
  tests/seed/settings/defines.inc.php
  tests/seed/settings/parameters.php
  vendor/.htaccess
Labels: 4.2.0, enhancement

#205 4.2.0 | getContent refactor with builders
  config/builder.yml
  config/provider.yml
  config/service.yml
  mollie.php
  src/Builder/Content/BaseInfoBlock.php
  src/Builder/Content/LogoInfoBlock.php
  src/Builder/Content/RoundingModeInfoBlock.php
  src/Builder/Content/SmartyCacheInfoBlock.php
  src/Builder/Content/SmartyForceCompileInfoBlock.php
  src/Builder/Content/UpdateMessageInfoBlock.php
  src/Provider/UpdateMessageProvider.php
  src/Provider/UpdateMessageProviderInterface.php
  src/Service/Content/SmartyTemplateParser.php
  src/Service/Content/TemplateParserInterface.php
  views/templates/admin/updateMessage.tpl
Labels: 4.2.0, WIP

#204 4.2.0 | Refactoring hookActionOrderStatusUpdate to have testable shipment information sender
  config/config.yml
  config/decoder.yml
  config/handler.yml
  config/provider.yml
  config/service.yml
  config/verification.yml
  mollie.php
  src/Adapter/ToolsAdapter.php
  src/Enum/PaymentTypeEnum.php
  src/Exception/ShipmentCannotBeSentException.php
  src/Handler/Api/OrderEndpointPaymentTypeHandler.php
  src/Handler/Api/OrderEndpointPaymentTypeHandlerInterface.php
  src/Handler/Shipment/ShipmentSenderHandler.php
  src/Handler/Shipment/ShipmentSenderHandlerInterface.php
  src/Provider/PaymentType/PaymentTypeIdentificationProvider.php
  src/Provider/PaymentType/RegularPaymentTypeIdentification.php
  src/Provider/Shipment/AutomaticShipmentSenderStatusesProvider.php
  src/Provider/Shipment/AutomaticShipmentSenderStatusesProviderInterface.php
  src/Service/ExceptionService.php
  src/Service/MollieOrderInfoService.php
  src/Service/Shipment/ShipmentInformationSender.php
  src/Service/Shipment/ShipmentInformationSenderInterface.php
  src/Service/ShipmentService.php
  src/Service/ShipmentServiceInterface.php
  src/Utility/Decoder/DecoderInterface.php
  src/Utility/Decoder/JsonDecoder.php
  src/Verification/PaymentType/CanBeRegularPaymentType.php
  src/Verification/PaymentType/PaymentTypeVerificationInterface.php
  src/Verification/Shipment/CanSendShipment.php
  src/Verification/Shipment/ShipmentVerificationInterface.php
  tests/Unit/Handler/Api/OrderEndpointPaymentTypeHandlerTest.php
  tests/Unit/Handler/Shipment/ShipmentSenderHandlerTest.php
  tests/Unit/Verification/PaymentType/CanBeRegularPaymentTypeTest.php
  tests/Unit/Verification/Shipment/CanSendShipmentTest.php
Labels: 4.2.0, refactoring

#198 4.2.0 | hookPaymentOptions refactoring
  config/builder.yml
  config/config.yml
  config/handler.yml
  config/payment_option_provider.yml
  config/validator.yml
  controllers/front/qrcode.php
  mollie.php
  src/Builder/Content/BaseInfoBlock.php
  src/Builder/Content/PaymentOption/IdealDropdownInfoBlock.php
  src/Config/Config.php
  src/Handler/PaymentOption/PaymentOptionHandler.php
  src/Handler/PaymentOption/PaymentOptionHandlerInterface.php
  src/Install/Installer.php
  src/Install/Uninstall.php
  src/Provider/PaymentFeeProvider.php
  src/Provider/PaymentFeeProviderInterface.php
  src/Provider/PaymentOption/BasePaymentOptionProvider.php
  src/Provider/PaymentOption/CreditCardPaymentOptionProvider.php
  src/Provider/PaymentOption/IdealPaymentOptionProvider.php
  src/Provider/PaymentOption/PaymentOptionProviderInterface.php
  src/Service/ConfigFieldService.php
  src/Service/PaymentMethod/PaymentMethodRestrictionValidation/VoucherPaymentMethodRestrictionValidator.php
  src/Service/SettingsSaveService.php
  tests/phpstan/phpstan1.6.1.23.neon
  views/templates/hook/addjsdef.tpl
  views/templates/hook/ideal_dropdown.tpl
  views/templates/hook/qr_code.tpl
Labels: 4.2.0, WIP, enhancement, refactoring

#208 4.2.0 | Adding unique log id to have duplicate errors
  src/Logger/PrestaLogger.php
Labels: 4.2.0, refactoring

#213 4.2.0 | Adding autoindex, appending Makefile to run script
  Makefile
  vendorBuilder/vendor/autoindex/.travis.yml
  vendorBuilder/vendor/autoindex/LICENSE
  vendorBuilder/vendor/autoindex/README.md
  vendorBuilder/vendor/autoindex/css/bootstrap.min.css
  vendorBuilder/vendor/autoindex/css/theme.css
  vendorBuilder/vendor/autoindex/fonts/glyphicons-halflings-regular.eot
  vendorBuilder/vendor/autoindex/fonts/glyphicons-halflings-regular.svg
  vendorBuilder/vendor/autoindex/fonts/glyphicons-halflings-regular.ttf
  vendorBuilder/vendor/autoindex/fonts/glyphicons-halflings-regular.woff
  vendorBuilder/vendor/autoindex/index.php
  vendorBuilder/vendor/autoindex/js/jquery.js
  vendorBuilder/vendor/autoindex/sources/index.php
Labels: 4.2.0, enhancement

#212 4.2.0 - MOL-379 - Belgium to Klarna pay later payment option
  src/Config/Config.php
  tests/Unit/Tools/UnitTestCase.php
Labels: 4.2.0, enhancement

#207 4.2.0 | Adding EnvironmentVersionSpecificValidator for payment methods
  config/provider.yml
  config/validator.yml
  src/Provider/EnvironmentVersionProvider.php
  src/Provider/EnvironmentVersionProviderInterface.php
  src/Service/PaymentMethod/PaymentMethodRestrictionValidation/BasePaymentMethodRestrictionValidator.php
  src/Service/PaymentMethod/PaymentMethodRestrictionValidation/EnvironmentVersionSpecificPaymentMethodRestrictionValidator.php
  src/Service/PaymentMethodService.php
  tests/Unit/Service/PaymentMethod/PaymentMethodRestrictionValidation/VersionSpecificPaymentRestrictionValidationTest.php
Labels: 4.2.0, refactoring

#217 added sentry on exception catches
  Makefile
  composer.json
  config/handler.yml
  controllers/front/payment.php
  mollie.php
  src/Config/Config.php
  src/Handler/ErrorHandler/ErrorHandler.php
  src/Install/Installer.php
  src/Service/ApiKeyService.php
  src/Service/ApiService.php
  src/Service/ShipmentService.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/sentry/sentry/AUTHORS
  vendor/sentry/sentry/CHANGELOG.md
  vendor/sentry/sentry/LICENSE
  vendor/sentry/sentry/Makefile
  vendor/sentry/sentry/README.md
  vendor/sentry/sentry/bin/sentry
  vendor/sentry/sentry/composer.json
  vendor/sentry/sentry/lib/Raven/Autoloader.php
  vendor/sentry/sentry/lib/Raven/Breadcrumbs.php
  vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php
  vendor/sentry/sentry/lib/Raven/Breadcrumbs/MonologHandler.php
  vendor/sentry/sentry/lib/Raven/Client.php
  vendor/sentry/sentry/lib/Raven/Compat.php
  vendor/sentry/sentry/lib/Raven/Context.php
  vendor/sentry/sentry/lib/Raven/CurlHandler.php
  vendor/sentry/sentry/lib/Raven/ErrorHandler.php
  vendor/sentry/sentry/lib/Raven/Exception.php
  vendor/sentry/sentry/lib/Raven/Processor.php
  vendor/sentry/sentry/lib/Raven/Processor/RemoveCookiesProcessor.php
  vendor/sentry/sentry/lib/Raven/Processor/RemoveHttpBodyProcessor.php
  vendor/sentry/sentry/lib/Raven/Processor/SanitizeDataProcessor.php
  vendor/sentry/sentry/lib/Raven/Processor/SanitizeHttpHeadersProcessor.php
  vendor/sentry/sentry/lib/Raven/Processor/SanitizeStacktraceProcessor.php
  vendor/sentry/sentry/lib/Raven/ReprSerializer.php
  vendor/sentry/sentry/lib/Raven/SanitizeDataProcessor.php
  vendor/sentry/sentry/lib/Raven/Serializer.php
  vendor/sentry/sentry/lib/Raven/Stacktrace.php
  vendor/sentry/sentry/lib/Raven/TransactionStack.php
  vendor/sentry/sentry/lib/Raven/Util.php
  vendor/sentry/sentry/lib/Raven/data/cacert.pem
  vendor/sentry/sentry/phpunit.xml
Labels: 4.2.0

#218 4.2.0 | Order total restriction update on upgrade
  upgrade/Upgrade-4.2.0.php
Labels: 4.2.0, enhancement

#219 4.2.0 | Segment usage update
  mollie.php
Labels: 4.2.0, refactoring
