Repository Invertus-mollie/PrestaShop, pull requests merged in 2021-01, with the labels that each got.

#225 added logic that when mollie order creation fails, it trys again whit…
  .github/workflows/deploy.yml
  controllers/front/payment.php
Labels: 4.2.0

#226 upgraded axios version to stable one
  views/js/dist/0.min.js
  views/js/dist/app.min.js
  views/js/dist/banks.min.js
  views/js/dist/carrierconfig.min.js
  views/js/dist/methodconfig.min.js
  views/js/dist/qrcode.min.js
  views/js/dist/transaction.min.js
  views/js/dist/transactionOrder.min.js
  views/js/dist/transactionRefund.min.js
  views/js/dist/updater.min.js
  views/js/dist/vendors~app.min.js
  views/js/dist/vendors~banks~carrierconfig~methodconfig~qrcode~transaction.min.js
  views/js/dist/vendors~banks~carrierconfig~methodconfig~qrcode~transaction~updater.min.js
  views/js/dist/vendors~banks~carrierconfig~methodconfig~transaction.min.js
  views/js/dist/vendors~banks~carrierconfig~methodconfig~transaction~updater.min.js
  views/js/dist/vendors~sweetalert.min.js
  views/js/dist/vendors~transactionOrder.min.js
  views/js/dist/vendors~transactionOrder~transactionRefund.min.js
  views/js/dist/vendors~transactionOrder~transactionRefund~updater.min.js
  views/js/package.json
Labels: 4.2.0

#222 4.2.0 | Adding tests to mail validation
  config/validator.yml
  src/Validator/MailValidatorInterface.php
  src/Validator/NewOrderMailValidator.php
  src/Validator/OrderConfMailValidator.php
  tests/Unit/Validator/NewOrderMailValidatorTest.php
  tests/Unit/Validator/OrderConfirmationMailValidatorTest.php
Labels: 4.2.0, refactoring

#227 added new script to update translations from new formated cvs file wi…
  bin/console
  config/command.yml
  src/Builder/Content/PaymentOption/index.php
  src/Builder/Content/index.php
  src/Command/UpdateTranslationsConsoleCommand.php
  src/Command/UploadTranslationsFromCsvFileConsoleCommand.php
  src/Enum/index.php
  src/Handler/Api/index.php
  src/Handler/CartRule/index.php
  src/Handler/ErrorHandler/index.php
  src/Handler/OrderTotal/index.php
  src/Handler/PaymentOption/index.php
  src/Handler/Shipment/index.php
  src/Provider/OrderTotal/index.php
  src/Provider/PaymentMethod/index.php
  src/Provider/PaymentOption/index.php
  src/Provider/PaymentType/index.php
  src/Provider/Shipment/index.php
  src/Service/Content/index.php
  src/Service/EntityManager/index.php
  src/Service/OrderTotal/index.php
  src/Service/PaymentMethod/PaymentMethodRestrictionValidation/index.php
  src/Service/Shipment/index.php
  src/Tracker/index.php
  src/Utility/Decoder/index.php
  src/Utility/NumberUtility.php
  src/Verification/OrderTotal/index.php
  src/Verification/PaymentType/index.php
  src/Verification/Shipment/index.php
  src/Verification/index.php
  translations/de.php
  translations/en.php
  translations/fr.php
  translations/nl.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: 4.2.0

#228 added env for sentry
  .env.dist
  .gitignore
  composer.json
  config/config.yml
  mollie.php
  src/Command/UploadTranslationsFromCsvFileConsoleCommand.php
  src/Config/Env.php
  src/Handler/ErrorHandler/ErrorHandler.php
  src/Service/ApiService.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/phpoption/phpoption/LICENSE
  vendor/phpoption/phpoption/Makefile
  vendor/phpoption/phpoption/composer.json
  vendor/phpoption/phpoption/src/PhpOption/LazyOption.php
  vendor/phpoption/phpoption/src/PhpOption/None.php
  vendor/phpoption/phpoption/src/PhpOption/Option.php
  vendor/phpoption/phpoption/src/PhpOption/Some.php
  vendor/vlucas/phpdotenv/LICENSE.txt
  vendor/vlucas/phpdotenv/composer.json
  vendor/vlucas/phpdotenv/src/Dotenv.php
  vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php
  vendor/vlucas/phpdotenv/src/Environment/Adapter/AdapterInterface.php
  vendor/vlucas/phpdotenv/src/Environment/Adapter/ApacheAdapter.php
  vendor/vlucas/phpdotenv/src/Environment/Adapter/ArrayAdapter.php
  vendor/vlucas/phpdotenv/src/Environment/Adapter/EnvConstAdapter.php
  vendor/vlucas/phpdotenv/src/Environment/Adapter/PutenvAdapter.php
  vendor/vlucas/phpdotenv/src/Environment/Adapter/ServerConstAdapter.php
  vendor/vlucas/phpdotenv/src/Environment/DotenvFactory.php
  vendor/vlucas/phpdotenv/src/Environment/DotenvVariables.php
  vendor/vlucas/phpdotenv/src/Environment/FactoryInterface.php
  vendor/vlucas/phpdotenv/src/Environment/VariablesInterface.php
  vendor/vlucas/phpdotenv/src/Exception/ExceptionInterface.php
  vendor/vlucas/phpdotenv/src/Exception/InvalidFileException.php
  vendor/vlucas/phpdotenv/src/Exception/InvalidPathException.php
  vendor/vlucas/phpdotenv/src/Exception/ValidationException.php
  vendor/vlucas/phpdotenv/src/Lines.php
  vendor/vlucas/phpdotenv/src/Loader.php
  vendor/vlucas/phpdotenv/src/Parser.php
  vendor/vlucas/phpdotenv/src/Regex/Error.php
  vendor/vlucas/phpdotenv/src/Regex/Regex.php
  vendor/vlucas/phpdotenv/src/Regex/Result.php
  vendor/vlucas/phpdotenv/src/Regex/Success.php
  vendor/vlucas/phpdotenv/src/Validator.php
Labels: 4.2.0

#231 fixed issue where ideal components didint work on ps16 and on ps17 if…
  src/Provider/PaymentOption/IdealPaymentOptionProvider.php
  src/Service/IssuerService.php
  upgrade/Upgrade-4.1.2.php
Labels: 4.3.0

#234 added country code for payment descriptions
  src/Builder/ApiTestFeedbackBuilder.php
  src/Utility/TextGeneratorUtility.php
  vendor/.htaccess
  views/templates/admin/_configure/helpers/form/form.tpl
  views/templates/admin/api_test_results.tpl
Labels: 4.3.0

#236 fixed issue with module upgrade
  mollie.php
Labels: 4.3.0, bug

#237 fixed issue where segment check would fail if another module had it
  mollie.php
  src/Builder/ApiTestFeedbackBuilder.php
Labels: bug
